[package]
name = "TPrust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.9"

[[bin]]
name = "seuillage"
path = "src/seuillage.rs"

[[bin]]
name = "palette"
path = "src/palette.rs"